//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finance
{
    using System;
    using System.Collections.Generic;
    
    public partial class bkp
    {
        public long id { get; set; }
        public Nullable<int> lg { get; set; }
        public Nullable<long> bkh { get; set; }
        public Nullable<long> rsh { get; set; }
        public string nnlg { get; set; }
        public Nullable<System.DateTime> datd { get; set; }
        public string comt { get; set; }
        public Nullable<double> snl { get; set; }
    }
}
