//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finance
{
    using System;
    using System.Collections.Generic;
    
    public partial class fin
    {
        public long id { get; set; }
        public Nullable<long> frm { get; set; }
        public string tbl { get; set; }
        public Nullable<long> vlt { get; set; }
        public Nullable<double> sm { get; set; }
    }
}
