//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finance
{
    using System;
    using System.Collections.Generic;
    
    public partial class klt
    {
        public long id { get; set; }
        public Nullable<int> grp { get; set; }
        public Nullable<long> idp { get; set; }
        public string name { get; set; }
        public string okpo { get; set; }
        public string knds { get; set; }
        public string snds { get; set; }
        public string chet { get; set; }
        public string bank { get; set; }
        public string mfob { get; set; }
        public string adft { get; set; }
        public string adur { get; set; }
        public string telf { get; set; }
        public string cont { get; set; }
        public string comt { get; set; }
        public Nullable<int> per { get; set; }
        public string full { get; set; }
        public Nullable<int> nds { get; set; }
        public Nullable<double> sld { get; set; }
        public string dsld { get; set; }
        public Nullable<int> bud { get; set; }
    }
}
