//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finance
{
    using System;
    using System.Collections.Generic;
    
    public partial class ksh
    {
        public long id { get; set; }
        public Nullable<int> op { get; set; }
        public Nullable<int> lg { get; set; }
        public Nullable<int> tp { get; set; }
        public Nullable<long> num { get; set; }
        public string ndoc { get; set; }
        public string ncht { get; set; }
        public Nullable<System.DateTime> datd { get; set; }
        public Nullable<System.DateTime> dusr { get; set; }
        public Nullable<long> klt { get; set; }
        public Nullable<long> vlt { get; set; }
        public Nullable<long> frm { get; set; }
        public Nullable<long> usr { get; set; }
        public string comt { get; set; }
        public Nullable<int> del { get; set; }
        public Nullable<long> rsh { get; set; }
    }
}
