//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finance
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    internal partial class orestEntities : DbContext
    {
        public orestEntities()
            : base("name=orestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bank> bank { get; set; }
        public virtual DbSet<bkh> bkh { get; set; }
        public virtual DbSet<klt> klt { get; set; }
        public virtual DbSet<ksh> ksh { get; set; }
        public virtual DbSet<prh> prh { get; set; }
        public virtual DbSet<rsh> rsh { get; set; }
        public virtual DbSet<bkp> bkp { get; set; }
        public virtual DbSet<fin> fin { get; set; }
        public virtual DbSet<frm> frm { get; set; }
        public virtual DbSet<imp> imp { get; set; }
        public virtual DbSet<kmt> kmt { get; set; }
        public virtual DbSet<prih> prih { get; set; }
        public virtual DbSet<prp> prp { get; set; }
    }
}
