//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finance
{
    using System;
    using System.Collections.Generic;
    
    public partial class prih
    {
        public long id { get; set; }
        public string dat { get; set; }
        public string datd { get; set; }
        public Nullable<long> klt { get; set; }
        public string chp { get; set; }
        public Nullable<long> idh { get; set; }
        public string tbl { get; set; }
        public Nullable<double> sm { get; set; }
        public Nullable<double> nds { get; set; }
        public Nullable<long> imp { get; set; }
        public string dchp { get; set; }
    }
}
