// <auto-generated />
namespace Finance.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class PaymentStatementsChanging1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PaymentStatementsChanging1));
        
        string IMigrationMetadata.Id
        {
            get { return "201809190546132_PaymentStatementsChanging1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
