// <auto-generated />
namespace Finance.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_RemovedCounterpartyComment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_RemovedCounterpartyComment));
        
        string IMigrationMetadata.Id
        {
            get { return "201808170523266_add_RemovedCounterparty.Comment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
